baseURL = 'https://underliner.studio/'
publishDir = "../dist"
enableEmoji = true
timeZone = "Europe/Prague"
defaultContentLanguage = "cs"
languageCode = "cs"
disableKinds = ["taxonomy"]

[params]
  socialMedia = [
    {name = "Instagram", url = "https://www.instagram.com/underliner_studio/"},
    {name = "Dribbble", url = "https://dribbble.com/underliner-studio"},
    {name = "x.com", url = "https://twitter.com/underlinerstdio"},
    {name = "LinkedIn", url = "https://www.linkedin.com/company/underliner-studio/"}
  ]

[permalinks]
  categories = "/blog/:slug/"
  posts = "/blog/:slug/"

[markup]
  [markup.tableOfContents]
    endLevel = 2
    ordered = false
    startLevel = 2

[languages]
  [languages.cs]
    languageName = "Čeština"
    weight = 1
    [languages.cs.menu]
      [[languages.cs.menu.main]]
        identifier = "home"
        name = "Home"
        URL = "/"
        weight = 1
        [languages.cs.menu.main.params]
          hidden = "true"
      [[languages.cs.menu.main]]
        identifier = "about"
        name = "O nás"
        URL = "/about/"
        weight = 2
      [[languages.cs.menu.main]]
        identifier = "why"
        name = "Proč"
        URL = "/why/"
        weight = 3
        [languages.cs.menu.main.params]
          minlogo = "true"
      [[languages.cs.menu.main]]
        identifier = "service"
        name = "Služby"
        URL = "/services/"
        weight = 4
      [[languages.cs.menu.main]]
        identifier = "blog"
        name = "Blog"
        URL = "/blog/"
        weight = 5
        [languages.cs.menu.main.params]
          hidden = "true"
      [[languages.cs.menu.main]]
        identifier = "contact"
        name = "Kontakt"
        URL = "/contact/"
        weight = 99
  # [languages.en]
  #   languageName = "English"
  #   weight = 2
  #   [languages.en.menu]
  #     [[languages.en.menu.main]]
  #       identifier = "about"
  #       name = "About"
  #       URL = "/en/about/"
  #       weight = 1
  #     [[languages.en.menu.main]]
  #       identifier = "why"
  #       name = "Why"
  #       URL = "/en/why/"
  #       weight = 2
  #       [languages.en.menu.main.params]
  #         minlogo = "true"
  #     # [[languages.en.menu.main]]
  #     #   identifier = "services"
  #     #   name = "Services"
  #     #   URL = "/en/services/"
  #     #   weight = 3
  #     # [[languages.en.menu.main]]
  #     #   identifier = "work"
  #     #   name = "Work"
  #     #   URL = "/en/work/"
  #     #   weight = 3
  #     [[languages.en.menu.main]]
  #       identifier = "contact"
  #       name = "Contact"
  #       URL = "/en/contact/"
  #       weight = 99

[minify]
  disableCSS = false
  disableHTML = false
  disableJS = false
  disableJSON = false
  disableSVG = false
  disableXML = false
  minifyOutput = true