baseURL = 'https://underliner.studio/'
publishDir = "../dist"
enableEmoji = true
timeZone = "Europe/Prague"
defaultContentLanguage = "cs"
languageCode = "cs"

disableKinds = ["taxonomy", "taxonomyTerm"]

[languages]
  [languages.cs]
    languageName = "Čeština"
    weight = 1
    [languages.cs.menu]
      [[languages.cs.menu.main]]
        identifier = "contact"
        name = "Kontakt"
        URL = "/contact/"
        weight = 99
  [languages.en]
    languageName = "English"
    weight = 2
    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "contact"
        name = "Contact"
        URL = "/en/contact/"
        weight = 99


[minify]
  minifyOutput = true