baseURL = 'https://underliner.studio/'
publishDir = "../dist"
enableEmoji = true
timeZone = "Europe/Prague"
defaultContentLanguage = "cs"
languageCode = "cs"


[menu]
  [[menu.main]]
    identifier = "homepage"
    URL = "/"
    weight = 1
  [[menu.main]]
    identifier = "about"
    name = "O nás"
    URL = "/o-nas/"
    weight = 2
  [[menu.main]]
    identifier = "contact"
    name = "Kontakt"
    URL = "/kontakt/"
    weight = 99

[minify]
  minifyOutput = true