[[headers]]
  for = "/fonts/Gilroy/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/css/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[build]
  comand = "npm run build"
  publish = "dist"
  [build.environment]
    HUGO_VERSION = "0.120.1"
[functions]
  directory = "functions/"